In [1]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
import pandas as pd
import folium
import re

In [9]:
import pandas as pd

# 定义要处理的文件列表
file_numbers = [3, 4, 5, 6, 7, 8, 10, 11, 12]
file_prefix = 'pems'
file_suffix = '_all_common_flow.csv'

# 遍历文件列表
for num in file_numbers:
    file_name = f'{file_prefix}{num:02d}{file_suffix}'
    # 读取CSV文件
    df = pd.read_csv(file_name)
    # 修改列名
    df = df.rename(columns={'Timestamp': 'date'})
    # 保存修改后的数据回CSV文件
    df.to_csv(file_name, index=False)

print("所有文件都已处理完毕。")

所有文件都已处理完毕。

In [8]:
pems05 = pd.read_csv('pems05_all_common_flow.csv')
pems05 = pems05.rename(columns={'Timestamp':'date'})
pems05.to_csv('pems05_all_common_flow.csv')
pems05

,date,500010092,500010093,500010101,500010102,500010121,500010122,500010142,500010143,500011021,...,501017022,501017023,501017032,501017033,501017042,501017043,501017051,501017052,501017061,501017062
0,2012-03-07 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2012-03-07 00:05:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2012-03-07 00:10:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2012-03-07 00:15:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2012-03-07 00:20:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1264646,2024-03-20 23:35:00,10.0,46.0,35.0,9.0,8.0,30.0,23.0,14.0,49.0,...,30.0,23.0,16.0,24.0,16.0,7.0,8.0,17.0,10.0,17.0
1264647,2024-03-20 23:40:00,16.0,46.0,32.0,17.0,19.0,35.0,36.0,15.0,51.0,...,23.0,22.0,16.0,23.0,12.0,14.0,14.0,11.0,10.0,12.0
1264648,2024-03-20 23:45:00,7.0,35.0,40.0,12.0,11.0,43.0,38.0,15.0,39.0,...,22.0,17.0,20.0,11.0,10.0,14.0,11.0,10.0,16.0,7.0
1264649,2024-03-20 23:50:00,9.0,18.0,23.0,16.0,15.0,21.0,33.0,18.0,44.0,...,21.0,17.0,14.0,16.0,8.0,10.0,9.0,9.0,12.0,13.0
1264650,2024-03-20 23:55:00,12.0,14.0,16.0,13.0,11.0,17.0,21.0,15.0,27.0,...,28.0,13.0,17.0,17.0,12.0,13.0,11.0,13.0,11.0,12.0